# PyTorch Basic

PyTorch 기초 사용법

In [1]:
import numpy as np

import torch

In [2]:
nums = torch.arange(9)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
nums.shape

torch.Size([9])

In [4]:
type(nums)

torch.Tensor

In [5]:
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [6]:
nums.reshape(3, 3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [7]:
randoms = torch.rand((3, 3))
randoms

tensor([[0.9980, 0.5157, 0.7732],
        [0.3402, 0.1538, 0.9305],
        [0.3062, 0.4852, 0.5842]])

In [8]:
zeros = torch.zeros((3, 3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [9]:
ones = torch.ones((3, 3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.zeros_like(ones) #기존 ones shape과 같은 zero 행렬을 생성

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
zeros.size()

torch.Size([3, 3])

# Operations

PyTorch로 수학연산

In [24]:
nums * 3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [25]:
nums = nums.reshape((3, 3))

In [26]:
nums + nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [27]:
result = torch.add(nums, 10)

In [28]:
result.numpy()

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]], dtype=int64)

## View

In [29]:
range_nums = torch.arange(9).reshape(3, 3)

In [30]:
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [31]:
range_nums.view(-1)# shape 펼치기

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
range_nums.view(1, 9)
# reshape과 비슷함.

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

# Slice and Index
## 행렬 구조 확인

In [33]:
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [34]:
nums[1]

tensor([3, 4, 5])

In [35]:
nums[1, 1]

tensor(4)

In [36]:
nums[1:, 1:]

tensor([[4, 5],
        [7, 8]])

In [37]:
nums[1:]

tensor([[3, 4, 5],
        [6, 7, 8]])

## Compile

numpy를 torch tensor로 불러오기

In [38]:
arr = np.array([1, 1, 1])

In [41]:
arr_torch = torch.from_numpy(arr)# numpy to torch

In [42]:
arr_torch.float()

tensor([1., 1., 1.])

In [44]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
#cuda 사용

In [48]:
arr_torch.to(device)
# 연산을 GPU에서 처리함

tensor([1, 1, 1], device='cuda:0', dtype=torch.int32)

In [47]:
device 
# GPU

'cuda'

# AutoGrad

## 기울기 구하기,

In [74]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
#requires_grad = true
print(x.grad_fn)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [81]:
y = x +2
y

##  y = x라하면,  위 라인과 동일한 tensor형태를 반환하나x에 추가로 변수를 기입하는경우 grad_fn이 활성화됨.
## backward 앞에 Add가 붙음. 즉 forward 로 add 연산이 붙었다는 뜻

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [82]:
print(y.grad_fn)

# y는 grad=True 속성을 갖는 2x2행렬

In [83]:
z = y * y * 3
out = z.mean()


In [85]:
print(z, out)
#z는 grad_fn 속성을 갖은 y가 여러번 곱해져 있어 grad_fn이  mul이 붙어있음
print(z.grad_fn)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [86]:
out.backward() #기울기 얻어보자

여기서 인풋은 x가되고, output은 out이되는데, out은 y에 대한 이차방정식.
이때, grad는 기울기를 구하는 함수,, 한편 out=(3y^2) / (4) = (3(x+2)^2)/4  (원소 4개이므로, 4로나눔)
이때 out의 x에 대한1차 미방은 6(x+2)/4가 됨. 즉 1.5(x+2)
x는 처음 1이었으므로, 3x1.5 = 4.5가 x.grad가 됨.
 grad는 결국 인풋값에 대한 기울기를 찾아야하므로, x.grad만 구함.
 


In [72]:
print(x.grad)
print(y.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
None


In [93]:
print(x.requires_grad)
print((x ** 2).requires_grad) # 2 star는 제곱임


True
True


In [94]:
with torch.no_grad():
    print((x ** 2).requires_grad)
    
    #torch.no_grad - > 테스트할때는 새로 grad구할필요 없으므로, 테스트시 사용

False
