In [4]:
import torch

In [3]:
import tensorflow as tf
import numpy as np

# Data type
   ## array 의 dtype을 확인

In [8]:
arr = np.array([[1.,2,3],[1,2,3]])

In [9]:
arr.dtype
# data 형태 확인
# 파이썬은 먼저 수를 넣으면 데이터타입이 알아서 정해지는스타일.. 다른언어는 미리 데이터형식 지정해줌


dtype('float64')

In [10]:
arr.astype('float32')
# data type 변경

array([[1., 2., 3.],
       [1., 2., 3.]], dtype=float32)

In [19]:
arr2 = arr.astype(np.int32)
arr2

array([[1, 2, 3],
       [1, 2, 3]])

In [18]:
arr2.dtype

dtype('int32')

In [20]:
arr.shape

(2, 3)

In [21]:
arr.ndim

2

In [22]:
len(arr.shape)

2

In [24]:
print(arr.size)
print(arr)


6
[[1. 2. 3.]
 [1. 2. 3.]]


# Reshape

In [28]:
arr = arr.reshape([1,6])
print(arr.shape)
print(arr)
#사이즈는 유지하고 모양만 변경

(1, 6)
[[1. 2. 3. 1. 2. 3.]]


In [29]:
arr = np.array([[1,2,3,],[1,2,3]])

In [34]:
arr3 = arr.reshape([6]).shape
print(arr3)
arr4= arr.reshape([6])
print(arr4)

(6,)
[1 2 3 1 2 3]


# Reshap, -1 활용

## reshape -1은 data dimension 모를때 사용
### row/column 중 하나만 값 지정하고 나머지 -1넣어주면, 정해진 값에 맞춰서 reshape 진행

In [43]:
arr = np.array([[1,2,3,],[1,2,3]])
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [51]:
print(arr.reshape(-1))
print(arr.reshape(-1).shape)
# 위 array 2x3이 reshape -1을 통해 1x6으로 바뀜. 
# 보통 -1만 사용하면, 1자배열로 바뀜

print(arr.reshape(1,-1))
print(arr.reshape(1,-1).shape)
# 1,-1하는경우 2x3에서 1x6으로변경
# 앞의 수를 1로 정해주면, 해당 row가 1인것이므로, 1x6으로 변경.

print(arr.reshape(-1,1))
print(arr.reshape(-1,1).shape)
# -1,1 하는경우 2x3에서, 6x1로 변경.
# -1에 해당하는부분은 자동맞춤이고, 뒤에 column size가 1이므로, 사이즈의 최대값을 row로 반환하여 정렬. (size = 6)

print('---------------')
print(arr.reshape(-1,3))
print(arr.reshape(-1,3).shape)
# -1부분은 알아서맞추고, column이 3. 따라서 2x3으로 정렬됨.


[1 2 3 1 2 3]
(6,)
[[1 2 3 1 2 3]]
(1, 6)
[[1]
 [2]
 [3]
 [1]
 [2]
 [3]]
(6, 1)
---------------
[[1 2 3]
 [1 2 3]]
(2, 3)


# random array 생성

In [5]:
arr = np.random.randn(8, 8)
arr.shape

(8, 8)

In [6]:
arr= arr.reshape([32,2])
arr.shape

(32, 2)

In [7]:
arr

array([[-1.34068861,  1.23789375],
       [ 0.45311872,  1.04223403],
       [-0.04452017, -0.40679634],
       [ 1.51513374,  0.09750298],
       [-0.23440999,  0.37924977],
       [ 0.30006504,  1.08926823],
       [-0.8880761 ,  0.10872841],
       [-0.86803599, -0.24424224],
       [-1.41699464,  0.55914047],
       [ 0.19015188, -1.98382674],
       [-0.57880018, -1.5669125 ],
       [-0.16969313, -1.83015722],
       [ 0.80571232,  1.50047134],
       [-1.09147822,  0.16147461],
       [ 0.19994186, -2.46644406],
       [-1.43027361, -0.38789752],
       [-0.63410044,  0.54242429],
       [ 2.59972773,  0.11006286],
       [-1.95546733, -0.97430866],
       [ 0.3736569 , -0.35651667],
       [-1.20969805,  0.52081778],
       [-1.56404655, -0.52140776],
       [-0.63875187,  0.03890819],
       [-0.62494279, -0.67251995],
       [ 0.38899254, -1.47664868],
       [ 0.47539173,  0.38884654],
       [-0.04762926, -0.6589114 ],
       [-0.96422773,  1.19100445],
       [-0.32823368,

# 3차원으로 확장

In [8]:
arr = arr.reshape(-1,2,2)
arr.shape

(16, 2, 2)

# Ravel


In [9]:
arr.shape

(16, 2, 2)

In [11]:
arr.ravel()
# 1차원배열로 바꿔줌

array([-1.34068861,  1.23789375,  0.45311872,  1.04223403, -0.04452017,
       -0.40679634,  1.51513374,  0.09750298, -0.23440999,  0.37924977,
        0.30006504,  1.08926823, -0.8880761 ,  0.10872841, -0.86803599,
       -0.24424224, -1.41699464,  0.55914047,  0.19015188, -1.98382674,
       -0.57880018, -1.5669125 , -0.16969313, -1.83015722,  0.80571232,
        1.50047134, -1.09147822,  0.16147461,  0.19994186, -2.46644406,
       -1.43027361, -0.38789752, -0.63410044,  0.54242429,  2.59972773,
        0.11006286, -1.95546733, -0.97430866,  0.3736569 , -0.35651667,
       -1.20969805,  0.52081778, -1.56404655, -0.52140776, -0.63875187,
        0.03890819, -0.62494279, -0.67251995,  0.38899254, -1.47664868,
        0.47539173,  0.38884654, -0.04762926, -0.6589114 , -0.96422773,
        1.19100445, -0.32823368,  0.73490756,  0.77222073, -3.0895895 ,
        0.52332788, -0.12640681,  1.55463527, -0.60644954])

In [14]:
arr.reshape(-1) == arr.ravel()   
# reshape(-1)과 ravel의 역할은 같다!

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
#다차원을 1차원으로 바꾸는경우가 있음

# np.expand_dims()

## size는 유지하고싶되, 차원수만 늘리고싶은 경우 사용

In [15]:
arr.shape

(16, 2, 2)

In [19]:
arr = np.expand_dims(arr, 0)
print(arr.shape)
print(arr)


(1, 1, 1, 1, 16, 2, 2)
[[[[[[[-1.34068861  1.23789375]
      [ 0.45311872  1.04223403]]

     [[-0.04452017 -0.40679634]
      [ 1.51513374  0.09750298]]

     [[-0.23440999  0.37924977]
      [ 0.30006504  1.08926823]]

     [[-0.8880761   0.10872841]
      [-0.86803599 -0.24424224]]

     [[-1.41699464  0.55914047]
      [ 0.19015188 -1.98382674]]

     [[-0.57880018 -1.5669125 ]
      [-0.16969313 -1.83015722]]

     [[ 0.80571232  1.50047134]
      [-1.09147822  0.16147461]]

     [[ 0.19994186 -2.46644406]
      [-1.43027361 -0.38789752]]

     [[-0.63410044  0.54242429]
      [ 2.59972773  0.11006286]]

     [[-1.95546733 -0.97430866]
      [ 0.3736569  -0.35651667]]

     [[-1.20969805  0.52081778]
      [-1.56404655 -0.52140776]]

     [[-0.63875187  0.03890819]
      [-0.62494279 -0.67251995]]

     [[ 0.38899254 -1.47664868]
      [ 0.47539173  0.38884654]]

     [[-0.04762926 -0.6589114 ]
      [-0.96422773  1.19100445]]

     [[-0.32823368  0.73490756]
      [ 0.77222073 -3

In [21]:
arr = arr.ravel()
arr

array([-1.34068861,  1.23789375,  0.45311872,  1.04223403, -0.04452017,
       -0.40679634,  1.51513374,  0.09750298, -0.23440999,  0.37924977,
        0.30006504,  1.08926823, -0.8880761 ,  0.10872841, -0.86803599,
       -0.24424224, -1.41699464,  0.55914047,  0.19015188, -1.98382674,
       -0.57880018, -1.5669125 , -0.16969313, -1.83015722,  0.80571232,
        1.50047134, -1.09147822,  0.16147461,  0.19994186, -2.46644406,
       -1.43027361, -0.38789752, -0.63410044,  0.54242429,  2.59972773,
        0.11006286, -1.95546733, -0.97430866,  0.3736569 , -0.35651667,
       -1.20969805,  0.52081778, -1.56404655, -0.52140776, -0.63875187,
        0.03890819, -0.62494279, -0.67251995,  0.38899254, -1.47664868,
        0.47539173,  0.38884654, -0.04762926, -0.6589114 , -0.96422773,
        1.19100445, -0.32823368,  0.73490756,  0.77222073, -3.0895895 ,
        0.52332788, -0.12640681,  1.55463527, -0.60644954])

In [22]:
arr.shape

(64,)

In [39]:
arr = np.expand_dims(arr, -1)
arr.shape

## 강좌에서는 차원 하나만붙었는데 예제에서는 3개씩붙음.
# 3개씩붙는게 아니라 초기화안해줘서 계속붙었음

(1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 64,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1)

In [35]:

arr = np.expand_dims(np.expand_dims(arr, -1),0)
arr.shape

#expand_dims는 나중에 따로 확인

(1, 1, 1, 1, 1, 1, 1, 1, 1, 64, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)