In [5]:
import numpy as np

zeros & once

In [4]:
z = np.zeros([3,3])
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
o = np.ones([2,2])
o

array([[1., 1.],
       [1., 1.]])

In [9]:
np.ones([10])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones([5,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# np.arange

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(4,9)

array([4, 5, 6, 7, 8])

In [20]:
arr = np.arange(9).reshape(3,3) 
arr
#np arange로 만들어진 1차원을 reshape을통해 모양변경

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Index

In [18]:
nums = [1,2,3,4,5]
nums[2:]

[3, 4, 5]

In [23]:
print(arr[1] , arr[0])

[3 4 5] [0 1 2]


In [26]:
arr[1][2]
# arr배열의 2행의 3번째원소는 5임, arr[1,2]로 해도됨

5

# Slicing


In [27]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [29]:
arr[1:, 1:]
# 행과열 0번째꺼 짜름 

array([[4, 5],
       [7, 8]])

# Boolean indexing

In [30]:
data = np.random.randn(3,3)
data

array([[ 0.93782751, -0.27920954,  1.28315198],
       [ 1.03587727,  0.3425377 , -0.35845107],
       [ 1.29045395,  0.32689858,  1.56669187]])

In [31]:
data <=0

array([[False,  True, False],
       [False, False,  True],
       [False, False, False]])

In [32]:
data[data<=0]

array([-0.27920954, -0.35845107])

In [34]:
data[data<=0]=1
data

array([[0.93782751, 1.        , 1.28315198],
       [1.03587727, 0.3425377 , 1.        ],
       [1.29045395, 0.32689858, 1.56669187]])

# Broadcast
### 행렬의 차원이 같지 않은경우, shape을 맞춰 연산

In [36]:
ar = np.arange(9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
ar+3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
ar*3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [41]:
print(ar + np.array([1,1,1]))
# 차원이 안맞아 복사해서 모든 행에 붙여서 더해버림
print(ar + np.array([1,2,3]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]


# Math function

In [ ]:
# np.add np.multiply 있긴한데 그냥 +, *해도 다 계산이 잘됨

In [46]:
arr = np.random.randint(2, size = 27).reshape(3,3,3)
arr2= np.random.randint(2, size=9).reshape(3,3)
print(arr)
print('-----')
print(arr2)

[[[0 1 1]
  [1 1 1]
  [0 0 1]]

 [[0 1 1]
  [0 1 1]
  [0 1 1]]

 [[1 1 0]
  [0 0 0]
  [1 0 1]]]
-----
[[0 1 0]
 [0 0 1]
 [0 1 0]]


In [47]:
print(arr.shape , arr2.shape)

(3, 3, 3) (3, 3)


In [48]:
# arr, arr2는 형태가 다른데 덧셈하면?
# 차원이 작은쪽애를 복사해서 큰차원에 덧붙임
arr+arr2

array([[[0, 2, 1],
        [1, 1, 2],
        [0, 1, 1]],

       [[0, 2, 1],
        [0, 1, 2],
        [0, 2, 1]],

       [[1, 2, 0],
        [0, 0, 1],
        [1, 1, 1]]])

In [51]:
np.sum(arr) 
# 모드 원소의 합 더함

16

In [52]:
np.sum(arr+ arr2, 0)
# 0차원에서 각지점의 값들 각각 다 더한값 반환. 그냥 스칼라값의 합

array([[1, 6, 2],
       [1, 2, 5],
       [1, 4, 3]])

In [56]:
print(np.sum(arr+arr2,1)) #각 열의 합
print(np.sum(arr+arr2,2)) # 각 행의 합
#print(np.sum(arr+arr2,3)) # 3은안됨
# 그냥 숫자 안주고 뒤에 axis=1,2 이런식으로 해도 됨

[[1 4 4]
 [0 5 4]
 [2 3 2]]
[[3 4 2]
 [3 3 3]
 [3 1 3]]


In [59]:
arr = np.array([1,2,3,1,4,8,8,9,10,2,4,5])
np.argmax(arr)
# max값은 10인데, 해당 10을 갖는 index 8을 반환

8