In [1]:
import numpy as np

In [4]:
arr  = np.array(5)
arr.shape
###0차원인 스칼라 5값만 넣었으므로, shape이 없음

()

In [5]:
arr.ndim

0

## 1차원
#### 스칼라는 0차원인데, 안에 리스트를 하나라도 씌우게되면 1차원이됨


In [8]:
arr2 = np.array ([5])
arr2.shape
#여기서 1은 값이 1개라는뜻

(1,)

In [10]:
arr2.ndim
# 1차원

1

In [12]:
arr3 = np.array ([1,2,3])
arr3.shape

(3,)

In [13]:
arr3.ndim

1

# 2차원
### 괄호를 두개치면 2차원

In [16]:
arr = np.array([[1,2,3]])
arr.shape
# 차원이 두개가 있고, 각 차원마다 값이 3개씩 있음.
#1x3

(1, 3)

In [24]:
arr = np.array([[1,2,3],[4,5,6],[3,6,1]])
print(arr)
print(arr.shape)   
# 1차원이 3개 모인 3 by 3 행렬
print(arr.ndim)
#2차원

[[1 2 3]
 [4 5 6]
 [3 6 1]]
(3, 3)
2


# 다차원

In [32]:
arr=np.array([[[[1,5,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]],[[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]])
arr.shape

# 3x3이 3개있는게 또 2번있는 모양.

(2, 3, 3, 3)

In [30]:
arr.ndim 
#4차원

4

In [33]:
#모양확인, 3x3행렬이 3개가있고,그게다시 두번있는것.
arr

array([[[[1, 5, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]],


       [[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]]])